
const TreasureList = [
    "Diamond Sword",
    "Go Up A Level",
    "Stand Arrow",
    "Samus's Helmet",
    "Deku Shield",
    "DK's Tie",
    "Sonic's Shoes",
    "Squarepants",


    // Temporary duplicates
    "Diamond Sword",
    "Go Up A Level",
    "Stand Arrow",
    "Samus's Helmet",
    "Deku Shield",
    "DK's Tie",
    "Sonic's Shoes",
    "Squarepants",
    "Diamond Sword",
    "Go Up A Level",
    "Stand Arrow",
    "Samus's Helmet",
    "Deku Shield",
    "DK's Tie",
    "Sonic's Shoes",
    "Squarepants",
    "Diamond Sword",
    "Go Up A Level",
    "Stand Arrow",
    "Samus's Helmet",
    "Deku Shield",
    "DK's Tie",
    "Sonic's Shoes",
    "Squarepants",
    "Diamond Sword",
    "Go Up A Level",
    "Stand Arrow",
    "Samus's Helmet",
    "Deku Shield",
    "DK's Tie",
    "Sonic's Shoes",
    "Squarepants",
    "Diamond Sword",
    "Go Up A Level",
    "Stand Arrow",
    "Samus's Helmet",
    "Deku Shield",
    "DK's Tie",
    "Sonic's Shoes",
    "Squarepants",
    "Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level","Go Up A Level",
]

const DoorList = [
    "Pogmin", 
    "Unpogmin",
    "Duck of Doom",
    "Mike Wazowski",

    // Temporary duplicates
    "Pogmin", 
    "Pogmin",
    "Pogmin", 
    "Pogmin", 
    "Pogmin", 
    "Pogmin", 
    "Pogmin",
    "Unpogmin",
    "Unpogmin",
    "Unpogmin", 
    "Unpogmin",
    "Unpogmin", 
    "Unpogmin",
    "Unpogmin", 
    "Mike Wazowski",
    "Mike Wazowski",
    "Mike Wazowski",
    "Mike Wazowski",
    "Mike Wazowski",
    "Mike Wazowski",
    "Mike Wazowski",
    "Mike Wazowski", 
    "Duck of Doom",
]

module.exports = { TreasureList, DoorList }