
const TreasureList = [
    "Diamond Sword",
    "Go Up A Level",

    // Temporary duplicates
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
    "Diamond Sword",
    "Go Up A Level",
]

const DoorList = [
    "Pogmin", 
    "Unpogmin", 
    "Warrior", 
    "Elf", 
    "Duck of Doom",

    // Temporary duplicates
    "Pogmin", 
    "Unpogmin", 
    "Pogmin", 
    "Unpogmin",
    "Pogmin", 
    "Unpogmin", 
    "Pogmin", 
    "Unpogmin",
    "Pogmin", 
    "Unpogmin", 
    "Pogmin", 
    "Unpogmin",
    "Pogmin", 
    "Unpogmin", 
    "Pogmin", 
    "Unpogmin",
    "Pogmin", 
    "Unpogmin", 
    "Pogmin", 
    "Unpogmin",
    "Pogmin", 
    "Unpogmin", 
    "Pogmin", 
    "Unpogmin",
    
    "Warrior", 
    "Elf", 
    "Duck of Doom",
]

module.exports = { TreasureList, DoorList }